### ISSUE TITLE
index nil value (lack of proper onesync support)

### ISSUE THREAD

**Issue by zek0** [Xinerki/kgv-blackjack#3]
Have problem in:

function SetPlayerBet(i, seat, bet, betId, double, split)
this line: 		players[i][num].bet = tonumber(bet)

example situation: If two player seat in table and bet, all ok, after if one player standup server get this error: attempt to index nil value (field '?'), and that it need restart script

**Comment by Xinerki** [comment]
are you using onesync?

**Comment by zek0** [comment]
yes

**Comment by Xinerki** [comment]
well that might be the problem

**Comment by zek0** [comment]
Thaks for answer. It is possible made function for reset table. Example if one of players standup, table is closed for all players and reset. Thats will be great. Thank you for great script.

**Comment by Xinerki** [comment]
i dont know actually, but i was thinking of doing onesync support sooner or later, so you might just have to wait a little
